# Generated by Django 5.2.17 on 2026-08-06 17:03

import chat.utils
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("identity", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("text", "Text"),
                            ("file", "File"),
                            ("voice", "Voice note"),
                        ],
                        default="text",
                        max_length=10,
                    ),
                ),
                ("text", models.TextField(blank=True)),
                (
                    "attachment",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=chat.utils.attachment_upload_path,
                    ),
                ),
                ("original_filename", models.CharField(blank=True, max_length=255)),
                ("content_type", models.CharField(blank=True, max_length=100)),
                ("size", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="identity.member",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
    ]
