# Generated by Django 5.2.17 on 2026-08-06 18:09

import django.db.models.deletion
from django.db import migrations, models


def backfill_sender_username(apps, schema_editor):
    """
    Snapshot each existing message's current sender username before the
    next operation loosens the FK to SET_NULL — otherwise any message from
    a member who later leaves (see identity.views.leave) would lose its
    attribution entirely instead of just losing the live relation.
    """
    Message = apps.get_model("chat", "Message")
    for message in Message.objects.select_related("sender").filter(sender__isnull=False):
        message.sender_username = message.sender.username
        message.save(update_fields=["sender_username"])


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0001_initial"),
        ("identity", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="sender_username",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.RunPython(backfill_sender_username, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="message",
            name="sender",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="messages",
                to="identity.member",
            ),
        ),
    ]
